language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: F9onIdveeZ4eWJOVnepx/m+zdNXZywXh+B4A7owZ0rQ+M6KTzUlsSVOOyKlbMIvtQE4TBtIsjYeNb0V6KVT8qx/3Z+7V/fwXGXcbVVJCvRL+xDcd0TNrrrXzFGIxNqfns21S7bS0Me1ztDfpwYxWvVOKeIgpgJPYeEYOk21DykLmfpS+Ez0Esl/Oc3R85kfIMXQr9NQ3QXuXSBJtCFCiwulEsyxzg0GkM4LtUXvibwwvYkhdgV/ONt82kHWAsg4o3khrVhXO7BdPn2DkN1wyAQwg8fHwx3lXnEa04oDc/VV6k8yC+U3iaMAVP7TwUPuiXT7t1vMQCJ2MtBJq7E6ezxHQeIrBSC8dxroskhnwZj7qgvOH3yjDaD3IjR0XnSA2/++TH628Xhpr9GSk1X977oXtF5mwAfqPyz1v0iQ2RIE4nV7WZqbrhTp/MwC2olDdBpqePEEQsl0+18ZmBgtp3j06pmmbBdVFpC/pezgU2WPeA7LJpV/jqNgWzmCja0Yhnzc15wlruJLmxXveSxaQ/pOn8+ugG7xr8yTGk6e8haVdeH92vETVaWp2FHJye+rAqvjsQ0+WFxKcHxzfjenz8RK3hYuQ67WzoWTBcS7KBj9cImzpbiZ6NYomFtTgemJyw460oMN3rxavzEU+8F2LEkxTsg9djdFIrOX8m6hHlRI=
  app: powerful-journey-05966